### PR TITLE
Avoid _SC_LEVEL1_DCACHE_LINESIZE for systems where it isn't present (…

### PR DESCRIPTION
**Pull request by Xyon**
…musl-libc, i.e. Alpine linux)

### CODE REVIEW

**Comment by aaronmdjones** [comment]
This patch is unacceptable for the following reasons:

1. You have declared a function within another function, something which requires stack trampolines (i.e. memory that is both writeable and executable) and is not supported by C compilers such as Clang.

2. You are using the function `sysfs__read_int` but I see no header file that defines it. You seem to have copied this code verbatim from [https://patchwork.kernel.org/patch/9226437/](https://patchwork.kernel.org/patch/9226437/) without supplying any of the necessary supporting infrastructure.

3. The function name you are using (again verbatim) shadows the `size_t` variable with the same name in the global scope.

**Comment by grawity** [comment]
nope.gif

However, does anything actually _use_ cacheline_size from mowgli? I'm not getting any results on Debian's codesearch, at least.

**Comment by aaronmdjones** [comment]
```
cacheline.c:30:8: warning: no previous extern declaration for non-static variable 'cacheline_size' [-Wmissing-variable-declarations]
size_t cacheline_size;
       ^
```

I doubt there are external users.

**Comment by aaronmdjones** [comment]
Nevermind, I just saw the function that returns its value.

**Comment by grawity** [comment]
Yes, but that function does not appear to be called from anywhere in any program (as far as Github's and Debian's code indexes go), so if it's write-only, it could be ripped out entirely. Does libmowgli have (or pretend to have) a stable ABI?

**Comment by aaronmdjones** [comment]
Not that I'm aware. We could go the `fopen(3)` route for `/sys` or rip it out entirely, I don't mind either way.

**Comment by Xyon** [comment]
For a bit of context, I was building this to fulfil the dependency for Atheme IRC services on an Alpine linux container. The patch worked (or at least, the thing compiled), so I wanted to at least raise the issue of it not building on that particular platform without a terrible workaround (which is not necessarily a massive issue, I accept).

I make no apologies for the quality of the code itself, since I didn't write it, but the shoehorning was a bit naff, I'll give you that.

**Comment by kaniini** [comment]
I'll just add _SC_LEVEL1_DCACHE_LINESIZE to Alpine.

**Comment by grawity** [comment]
> The function name you are using (again verbatim) shadows the size_t variable with the same name in the global scope.

I think that was supposed to be "shadows the cacheline_size variable". It's an integer, and then suddenly you're redeclaring it as a function. That doesn't give the results you might be expecting.

**Comment by Xyon** [comment]
That makes more sense, thanks @grawity. I admit, it did look a bit odd when I was copying it, but hey ho.

**Pull request closed without merging**
